config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/team' => 'static_pages#team'
  get '/about' => 'static_pages#about'
  get '/careers' => 'static_pages#careers'
  get '/viking' => 'static_pages#viking'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def team
  end
  
  def viking
  end
  
  def about
  end
  
  def careers
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="footer-logo">
    <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt="">
  </div>
  <div class="footer-links">
    <ul>
      <li><h3>Company</h3></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Careers", careers_path %></li>
        <li><%= link_to "Team", team_path %></li>
    </ul>
    <ul>
      <li><h3>Social</h3></li>
      <li><%= link_to "Facebook", 'https://www.facebook.com/ShieldBreakStudios' %></li>
      <li><%= link_to "Twitter", 'https://twitter.com/Shield_Break' %></li>
      <li><%= link_to "Twitch", '#' %></li>
    </ul>
  </div>
  <hr>
  <p>Copyright © Shield Break Studios 2013-2014. All Rights Reserved</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navigation">
  <div class="menu-wrapper">
    <a href=root class="logo">
      <%= image_tag("shield_logo.png", :alt => "shield_logo") %>
    </a>
    <p class="navigation-menu-button" id="js-mobile-menu">MENU</p>
    <div class="nav">
    <ul id="navigation-menu">
      <li><%= link_to "Project Viking", viking_path %>
      <li><%= link_to "Team", team_path %></li>
      <li><a href="mailto:info@shieldbreak.com">Contact</a></li>
      <li class="sign-up"><a href="javascript:void(0)">Beta</li>
    </ul>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shieldbreak</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <section class="wrapper">
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </section>
</body>
</html>

app/views/static_pages/home.html.erb
<div class="hero">
  <div class="hero-inner">
    <a href="" class="hero-logo"><img src="http://shieldbreak.com/img/shieldbreak.png" alt=""></a>
    <div class="hero-copy">
    </div>
    <%= button_to "Twitter", 'https://www.twitter.com/Shield_Break' %>
  </div>
</div>

<script>
  $(function() {
    var menu = $('#navigation-menu');
    var menuToggle = $('#js-mobile-menu');

    $(menuToggle).on('click', function(e) {
      e.preventDefault();
      menu.slideToggle(function(){
        if(menu.is(':hidden')) {
          menu.removeAttr('style');
        }
      });
    });
  });
</script>

app/views/static_pages/team.html.erb
<div class="grid-items">
  <a href="javascript:void(0)" class="grid-item">
    <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt="">
    <h1>Grid Item</h1>
    <p>Lorem ipsum dolor sit amet, elit. Rem, illum.</p>
  </a>
  <a href="javascript:void(0)" class="grid-item">
    <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt="">
    <h1>Grid Item</h1>
    <p>Lorem ipsum dolor sit amet, elit. Rem, illum.</p>
  </a>
  <a href="javascript:void(0)" class="grid-item">
    <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt="">
    <h1>Grid Item</h1>
    <p>Lorem ipsum dolor sit amet, elit. Rem, illum.</p>
  </a>
  <a href="javascript:void(0)" class="grid-item">
    <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt="">
    <h1>Grid Item</h1>
    <p>Lorem ipsum dolor sit amet, elit. Rem, illum.</p>
  </a>
  <a href="javascript:void(0)" class="grid-item">
    <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt="">
    <h1>Grid Item</h1>
    <p>Lorem ipsum dolor sit amet, elit. Rem, illum.</p>
  </a>      
  <a href="javascript:void(0)" class="grid-item">
    <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt="">
    <h1>Grid Item</h1>
    <p>Lorem ipsum dolor sit amet, elit. Rem, illum.</p>
  </a>  
  <a href="javascript:void(0)" class="grid-item">
    <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt="">
    <h1>Grid Item</h1>
    <p>Lorem ipsum dolor sit amet, elit. Rem, illum.</p>
  </a>
  <a href="javascript:void(0)" class="grid-item">
    <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt="">
    <h1>Grid Item</h1>
    <p>Lorem ipsum dolor sit amet, elit. Rem, illum.</p>
  </a>
  <a href="javascript:void(0)" class="grid-item">
    <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt="">
    <h1>Grid Item</h1>
    <p>Lorem ipsum dolor sit amet, elit. Rem, illum.</p>
  </a>   
  <a href="javascript:void(0)" class="grid-item">
    <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt="">
    <h1>Grid Item</h1>
    <p>Lorem ipsum dolor sit amet, elit. Rem, illum.</p>
  </a>
  <a href="javascript:void(0)" class="grid-item">
    <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt="">
    <h1>Grid Item</h1>
    <p>Lorem ipsum dolor sit amet, elit. Rem, illum.</p>
  </a>
  <a href="javascript:void(0)" class="grid-item">
    <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt="">
    <h1>Grid Item</h1>
    <p>Lorem ipsum dolor sit amet, elit. Rem, illum.</p>
  </a>   
</div>